core/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^user/', include('registration.backends.simple.urls')),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^school/create/$', login_required(SchoolCreateView.as_view()) , name='school_create'),
    url(r'^school/$', login_required(SchoolListView.as_view()) , name='school_list'),
    url(r'^school/(?P<pk>\d+)/$', login_required(SchoolDetailView.as_view()) , name='school_detail'),
    url(r'^school/update/(?P<pk>\d+)/$', login_required(SchoolUpdateView.as_view()) , name='school_update'),
    url(r'^school/delete/(?P<pk>\d+)/$', login_required(SchoolDeleteView.as_view()) , name='school_delete'),
    url(r'^school/(?P<pk>\d+)/review/create/$', login_required(ReviewCreateView.as_view()) , name='review_create'),
    url(r'^school/(?P<school_pk>\d+)/review/update/(?P<review_pk>\d+)/$', login_required(ReviewUpdateView.as_view()) , name='review_update'),
    url(r'^school/(?P<school_pk>\d+)/review/delete/(?P<review_pk>\d+)/$', login_required(ReviewDeleteView.as_view()) , name='review_delete'),
    url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
    url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
    url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()),  name='user_update'),
    url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
    url(r'^search/$', login_required(SearchSchoolListView.as_view()), name='search'),

)

qandu_final/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),


]

core/models.py
from django.db import models

from django.contrib.auth.models import User

from django.core.urlresolvers import reverse
VISIBILITY_CHOICES = (
(0, 'Public'),
(1, 'Anonymous'),
)


# Create your models here.

class School(models.Model):
  title = models.CharField(max_length=300)
  description = models.TextField(null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User)
  visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

  def __unicode__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("school_detail", args=[self.id])

class Review(models.Model):
    school = models.ForeignKey(School)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

    def __unicode__(self):
        return self.text

class Vote(models.Model):
    user = models.ForeignKey(User)
    school = models.ForeignKey(School, blank=True, null=True)
    review = models.ForeignKey(Review, blank=True, null=True)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/school/school_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class= "lead"> Are you sure you want to delete "{{ school.title }}? "</p>
<form method="post" action="">
    {% csrf_token %}
<button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/school/school_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ school.title }}</h1>
<p>{{ school.description }}</p>
<p>Asked by <a href="{% url 'user_detail' slug=school.user.username %}">{{ school.user.username }}</a> on {{ school.created_at }}</p>

{% if school.user == user %}
<p><a href="{% url 'school_update' pk=school.id %}">Edit school</a></p>

<p><a href="{% url 'school_delete' pk=school.id %}">Delete school</a></p>


{% endif %}

{% if reviews.count > 0 %}
<h3> {{ reviews.count }} Review{{ reviews.count|pluralize }}:</h3>
{% endif %}
{% for review in reviews %}
<div class="panel">
    <p>{{ review.text }}</p>

    {% if review.user == user %}
    <p><a href="{% url 'review_update' question_pk=school.id review_pk=review.id %}">Edit review</a></p>
    <p><a href="{% url 'review_delete' question_pk=school.id review_pk=review.id %}">Delete review</a></p>
    {% endif %}

    <p>Reviewed {% if review.visibility == 0 %} by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> {% endif %} on {{ review.created_at }} ({{ review.vote_set.all.count }} Vote{{ review.vote_set.all.count|pluralize }})</p>

     <form method="post" action="{% url 'vote' %}">
          <span class="badge">{{ review.vote_set.all.count }} Vote{{  review.vote_set.all.count|pluralize }}</span>
          {% csrf_token %}
          <input type="hidden" name="review" value="{{ review.id }}" />
          <input type="hidden" name="school" value="{{ school.id }}" />
          <input type="hidden" name="user" value="{{ user.id }}" />
          {% if review in user_votes %}
            <button class="btn btn-link">
              <span class="glyphicon glyphicon-thumbs-down"></span>
            </button>
          {% else %}
            <button class="btn btn-link">
              <span class="glyphicon glyphicon-thumbs-up"></span>
            </button>
        {% endif %}
     </form>

</div>
{% endfor %}
{% if not user_reviews %}
<p><a href="{% url 'review_create' pk=school.id %}">Write review</a></p>
{% endif %}
{% endblock %}

templates/school/school_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class= "row" >
      <div class="col-lg-6">
          <form method="post" action="" >
                      {% csrf_token %}
                      {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
      </div>
</div>
{% endblock %}

templates/school/school_list.html
{% extends 'base.html' %}
{% block content %}
{% for school in object_list %}
<div class="panel">

   <h3><a href="{{ school.get_absolute_url }}">{{ school.title }}</a></h3>
   <p>Asked by <a href="{% url 'user_detail' slug=school.user.username %}">{{ school.user.username }}</a> on {{ school.created_at }}</p>
   <form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ school.review_set.all.count }} Review{{  school.review_set.all.count|pluralize }}</span>
    <span class="badge">{{ school.vote_set.all.count }} Vote{{ school.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="school" value="{{ school.id }}" />
    <input type="hidden" name="user" value="{{ user.id }}" />
        {% if school in user_votes %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-down"></span>
        </button>
        {% else %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
        {% endif %}
    </form>


</div>

{% empty %}
<p>No results found.</p>

{% endfor %}

{% if is_paginated %}
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}>Next</a></li>
        {% endif %}
    </ul>

{% endif %}


{% endblock %}